# Generated by Django 4.1 on 2022-08-09 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendAPI', '0002_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Name',
        ),
    ]
