# Generated by Django 4.1 on 2022-08-09 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendAPI', '0006_diet_dailydiet_recipe_dailydiet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Challenges/')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
