# Generated by Django 4.1 on 2022-08-10 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendAPI', '0009_water_user_dairy'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='exercises',
            field=models.ManyToManyField(blank=True, related_name='users', to='backendAPI.exercise'),
        ),
    ]
