# Generated by Django 4.1 on 2022-08-10 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendAPI', '0012_userchallenge_userexercise_delete_favoriterecipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dietType',
            field=models.CharField(choices=[('CLASSIC', 'Classic'), ('LOW CARB', 'Low Carb'), ('LOW FAT', 'Low Fat'), ('HIGH PROTEIN', 'High Protein'), ('VEGAN', 'Vegan'), ('VEGETERIAN', 'Vegetarain')], default='CLASSIC', max_length=20),
        ),
    ]
