# Generated by Django 4.1 on 2022-08-10 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendAPI', '0013_alter_user_diettype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='ilnesses',
            field=models.CharField(choices=[('NO', 'None'), ('DI', 'Diabates'), ('CH', 'Cholesterol')], default='NO', max_length=20),
        ),
    ]
