# Generated by Django 4.1 on 2022-08-11 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendAPI', '0014_alter_user_birthdate_alter_user_ilnesses'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='email@gmail.com', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='0000000000', max_length=255),
        ),
    ]
